
import { Router } from "express";

const router = Router();

router.get("/test/generate", (_req, res) => {
  res.json({
    id: "test-123",
    title: "Placeholder Handmade Mug",
    price: 24.99,
    currency: "USD",
    images: [
      "https://picsum.photos/seed/resell-suite/600/600"
    ],
    description: "A lovely placeholder item generated by the backend stub."
  });
});

export default router;
